//pipeline starts
pipeline {

   agent any
   environment{
        DOCKER_REPO = 'vivekbangare2492/sogan'
   }
   stages {
    
       stage('SCM clone') {
            steps {
                git 'https://github.com/spring-io/sagan.git'
            }
        }
        stage('Build Artifact') {
            steps {
		// considering the Dockerfile is in same folder and
		// docker is installed on same machine
                sh "docker build -t ${env.DOCKER_REPO}:${env.BUILD_NUMBER} ."
            }
        }
        stage('Push Image') {
            steps {
                sh "docker push ${env.DOCKER_REPO}:${env.BUILD_NUMBER}"
            }
        }
        stage('Execute') {
            steps {
		//considering the minikube is installed on same machine
                
 		sh "helm install sagan --set image.tag=${env.BUILD_NUMBER} sogan-helm"

		// if sagan  chart already deployed then we can used only upgrade command rather than install
	        // sh "helm upgrade sagan --set image.tag=${env.BUILD_NUMBER} sogan-helm"
            }
        }
    }
}
